export const plans = [
    {
        label: "TRIAL OFFER",
        price: "₹150",
        crossedLabel: null,
        consultations: "2 consultations",
        validity: "Valid 30 days",
        savings: null,
        highlight: false,
        tagline: "Try before you subscribe",
        cta: "Initiate",
    },
    {
        label: "REGULAR · 3 MONTHS",
        price: "₹300",
        crossedLabel: "REGULAR",
        consultations: "5 consultations",
        validity: "Valid 90 days",
        savings: "You save ₹1,200",
        highlight: false,
        tagline: null,
        cta: "Initiate",
    },
    {
        label: "REGULAR · 6 MONTHS",
        price: "₹600",
        crossedLabel: "REGULAR",
        consultations: "11 consultations",
        validity: "Valid 180 days",
        savings: "You save ₹2,700",
        highlight: true,
        tagline: null,
        cta: "Initiate",
    },
    {
        label: "REGULAR · 9 MONTHS",
        price: "₹900",
        crossedLabel: "REGULAR",
        consultations: "18 consultations",
        validity: "Valid 270 days",
        savings: "You save ₹4,500",
        highlight: false,
        tagline: null,
        cta: "Initiate",
    },
];