export const plans = [
    {
        label: "",
        price: "₹150",
        consultations: "2 consultations",
        validity: "Validity - 30 days",
        savings: null,
        highlight: false,
        tagline: "Try before you subscribe",
    },
    {
        label: "",
        price: "₹300",
        consultations: "5 consultations",
        validity: "Validity - 90 days",
        savings: "You save ₹1,200",
        highlight: false,
        tagline: null,
    },
    {
        label: "",
        price: "₹600",
        consultations: "11 consultations",
        validity: "Validity - 180 days",
        savings: "You save ₹2,700",
        highlight: true,
        tagline: null,
    },
    {
        label: "",
        price: "₹900",
        consultations: "18 consultations",
        validity: "Validity - 270 days",
        savings: "You save ₹4,500",
        highlight: false,
        tagline: null,
    },
];